# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

---
platform: linux

params:
  CSP_API_TOKEN: ((marketplace_api_token))
  MARKETPLACE_ENV:
  PRODUCT_SLUG:

inputs:
  - name: version

run:
  path: bash
  args:
    - -xc
    - |
      export VERSION=$(cat version/version)

      mkpcli product list-versions --debug --debug-request-payloads --product "${PRODUCT_SLUG}" | grep "${VERSION}"
      if [[ $? -ne 0 ]] ; then
        set -e
        mkpcli product add-version --debug --debug-request-payloads --product "${PRODUCT_SLUG}" --product-version "${VERSION}"
        mkpcli product list-versions --debug --debug-request-payloads --product "${PRODUCT_SLUG}" | grep "${VERSION}"
      fi
