# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/golang
    tag: 1.16
    username: ((harbor.username))
    password: ((harbor.token))

inputs:
  - name: source
  - name: version

outputs:
  - name: build

run:
  path: /bin/bash
  dir: source
  args:
    - -exc
    - |
      export VERSION=$(cat ../version/version)
      make build-all
      cp build/* ../build
