# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

---
platform: linux

params:
  CSP_API_TOKEN: ((marketplace_api_token))
  MARKETPLACE_ENV:
  PRODUCT_SLUG:
  PRODUCT_VERSION:

inputs:
  - name: source

run:
  path: source/ci/tasks/download-chart.sh
