# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

---
platform: linux

params:
  CSP_API_TOKEN: ((marketplace_api_token))
  MARKETPLACE_ENV:
  PRODUCT_SLUG:
  PRODUCT_VERSION:

run:
  path: bash
  args:
    - -exc
    - |
      set -ex

      # Get the ID for the first file
      FILE_ID=$(mkpcli ova list --debug --debug-request-payloads --product "${PRODUCT_SLUG}" --product-version "${PRODUCT_VERSION}" --output json | jq -r .[0].fileid)

      # Download the file
      mkpcli ova download --debug --debug-request-payloads \
        --product "${PRODUCT_SLUG}" --product-version "${PRODUCT_VERSION}" \
        --file-id "${FILE_ID}" \
        --filename my-file.ova

      # Downloaded file is a real OVA
      test -f my-file.ova
