# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

---
platform: linux

params:
  CSP_API_TOKEN: ((marketplace_api_token))
  MARKETPLACE_ENV:
  PRODUCT_SLUG:
  PRODUCT_VERSION:

run:
  path: bash
  args:
    - -exc
    - |
      set -ex

      # Get the ID for the first file
      IMAGES=$(mkpcli container-image list --debug --debug-request-payloads --product "${PRODUCT_SLUG}" --product-version "${PRODUCT_VERSION}" --output json)
      IMAGE_URL=$(echo ${IMAGES} | jq -r .dockerurlsList[0].url)
      IMAGE_TAG=$(echo ${IMAGES} | jq -r .dockerurlsList[0].imagetagsList[0].tag)

      # Download the image
      mkpcli container-image download --debug --debug-request-payloads \
        --product "${PRODUCT_SLUG}" --product-version "${PRODUCT_VERSION}" \
        --image-repository "${IMAGE_URL}" --tag "${IMAGE_TAG}" \
        --filename my-container-image.tar

      # Downloaded file is a real docker image
      test -f my-container-image.tar
      tar tvf my-container-image.tar manifest.json
