# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/golang
    tag: 1.16
    username: ((harbor.username))
    password: ((harbor.token))

params:
  CSP_API_TOKEN:
  MARKETPLACE_HOST:

inputs:
  - name: source

run:
  path: make
  dir: source
  args: [test]
