# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

---
platform: linux

params:
  CSP_API_TOKEN: ((marketplace_api_token))
  MARKETPLACE_ENV:
  PRODUCT_SLUG:

inputs:
  - name: version
  - name: chart

run:
  path: bash
  args:
    - -exc
    - |
      set -ex
      VERSION=$(cat version/version)
      TEST_CHART_URL="${TEST_REPO_URL}/${TEST_CHART_NAME}-${VERSION}.tgz"

      # Get the list of charts
      mkpcli chart list --debug --debug-request-payloads \
        --product "${PRODUCT_SLUG}" --product-version "${VERSION}"

      # Upload a chart
      mkpcli chart attach --debug --debug-request-payloads \
        --product "${PRODUCT_SLUG}" --product-version "${VERSION}" \
        --chart "chart/*.tgz" --readme "helm install it"

      # Get the list of charts
      mkpcli chart list --debug --debug-request-payloads \
        --product "${PRODUCT_SLUG}" --product-version "${VERSION}" | grep -v "does not have any charts"
