# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

---
platform: linux

params:
  CSP_API_TOKEN: ((marketplace_api_token))
  MARKETPLACE_ENV:
  PRODUCT_SLUG:

inputs:
  - name: version
  - name: ova

run:
  path: bash
  args:
    - -exc
    - |
      set -ex
      VERSION=$(cat version/version)

      # Get the list of OVAs
      mkpcli ova list --debug --debug-request-payloads \
        --product "${PRODUCT_SLUG}" --product-version "${VERSION}"

      # Upload an OVA
      mkpcli ova attach --debug --debug-request-payloads \
        --product "${PRODUCT_SLUG}" --product-version "${VERSION}" \
        --ova-file ova/*.ova

      # Get the list of OVAs
      mkpcli ova list --debug --debug-request-payloads \
        --product "${PRODUCT_SLUG}" --product-version "${VERSION}" | grep -v "does not have any OVAs"
