---
platform: linux

inputs:
  - name: source
  - name: marketplace-source

outputs:
  - name: source

run:
  path: /bin/bash
  args:
    - -exc
    - |
      mkdir protoc-output
      protoc \
        --proto_path=marketplace-source/protobufs \
        --go_out=protoc-output \
        --go_opt=Mcatalog.proto=gitlab.eng.vmware.com/marketplace-partner-eng/marketplace-cli/v2/apps \
        --go_opt=Mparams.proto=gitlab.eng.vmware.com/marketplace-partner-eng/marketplace-cli/v2/params \
        marketplace-source/protobufs/catalog.proto \
        marketplace-source/protobufs/params.proto

      cp protoc-output/gitlab.eng.vmware.com/marketplace-partner-eng/marketplace-cli/v2/*/* source/models
      cd source/models

      protoc-go-inject-tag -verbose -input catalog.pb.go
      sed --in-place --expression "s/^package apps$/package models/" catalog.pb.go
      sed --in-place --expression '/params "gitlab.eng.vmware.com\/marketplace-partner-eng\/marketplace-cli\/v2\/params"/d' catalog.pb.go
      sed --in-place --expression "s/params.Params/Params/" catalog.pb.go
      protoc-go-inject-tag -verbose -input params.pb.go
      sed --in-place --expression "s/^package params$/package models/" params.pb.go

      cd ..
      make lint  # This will apply style formatting to the new model files

      git config --global user.email "tanzu-isv-engineering@groups.vmware.com"
      git config --global user.name "Tanzu ISV Engineering via Concourse"
      git add .
      if ! git diff --staged --quiet ; then
        git commit -m "Update models from CSP Marketplace"
      fi
