# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause

---
resource_types:
  - name: helm-chart
    type: registry-image
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/jghiloni/helm-chart-resource
      tag: v0.1.1
      username: ((harbor.username))
      password: ((harbor.token))

  - name: pull-request
    type: docker-image
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/teliaoss/github-pr-resource
      tag: v0.23.0
      username: ((harbor.username))
      password: ((harbor.token))

resources:
  - name: source
    type: git
    icon: github
    source:
      uri: git@github.com:vmware-labs/marketplace-cli.git
      private_key: ((github.private_key))
      branch: main

  - name: pull-requests
    type: pull-request
    icon: github
    check_every: 1m
    source:
      repository: vmware-labs/marketplace-cli
      access_token: ((github.access_token))

  - name: version
    type: semver
    icon: github
    source:
      driver: git
      uri: git@github.com:vmware-labs/marketplace-cli.git
      private_key: ((github.private_key))
      branch: main
      file: version
      commit_message: "[ci skip] bump version to %version%"

  - name: mkpcli
    type: registry-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/tanzu_isv_engineering/mkpcli
      username: ((harbor.username))
      password: ((harbor.token))

  - name: mkpcli-public
    type: registry-image
    icon: docker
    source:
      repository: projects.registry.vmware.com/tanzu_isv_engineering/mkpcli
      username: ((harbor-public.username))
      password: ((harbor-public.token))

  - name: release
    type: github-release
    icon: github
    source:
      owner: vmware-labs
      repository: marketplace-cli
      access_token: ((github.access_token))

  - name: test-container-product-version
    type: semver
    icon: gitlab
    source:
      driver: git
      uri: git@gitlab.eng.vmware.com:marketplace-partner-eng/test-products.git
      private_key: ((gitlab.private_key))
      branch: master
      file: test-container-product/version
      commit_message: "[ci skip] Updating to version %version%"

  - name: nginx-image
    type: registry-image
    icon: docker
    source:
      repository: bitnami/nginx
      tag: 1.21.1

  - name: nginx-chart
    type: helm-chart
    icon: kubernetes
    source:
      repository_url: https://charts.bitnami.com/bitnami
      chart: nginx

  - name: test-chart-product-version
    type: semver
    icon: gitlab
    source:
      driver: git
      uri: git@gitlab.eng.vmware.com:marketplace-partner-eng/test-products.git
      private_key: ((gitlab.private_key))
      branch: master
      file: test-chart-product/version
      commit_message: "[ci skip] Updating to version %version%"

  - name: test-ova-product-source
    type: git
    icon: gitlab
    source:
      uri: git@gitlab.eng.vmware.com:marketplace-partner-eng/test-products.git
      private_key: ((gitlab.private_key))
      branch: master
      paths:
        - test-ova-product/*
        - test-ova-product/**

  - name: test-ova-product-version
    type: semver
    icon: gitlab
    source:
      driver: git
      uri: git@gitlab.eng.vmware.com:marketplace-partner-eng/test-products.git
      private_key: ((gitlab.private_key))
      branch: master
      file: test-ova-product/version
      commit_message: "[ci skip] Updating to version %version%"

  - name: daily
    type: time
    icon: clock-outline
    source:
      start: 5:00 AM
      stop: 6:00 PM
      location: US/Central

jobs:
  - name: test
    plan:
      - get: daily
        trigger: true
      - get: source
        trigger: true
      - task: run-tests
        file: source/ci/tasks/test.yaml
        params:
          CSP_API_TOKEN: ((marketplace_api_token))
          MARKETPLACE_ENV: staging

  - name: test-pull-request
    serial: true
    plan:
      - in_parallel:
          - get: source
            resource: pull-requests
            trigger: true
            version: every
            params:
              integration_tool: rebase
            on_success:
              put: pull-requests
              inputs: detect
              params:
                path: source
                status: pending
            on_failure:
              put: pull-requests
              inputs: detect
              params:
                path: source
                context: merge-conflict
                status: failure
      - do:
        - task: run-tests
          file: source/ci/tasks/test.yaml
          params:
            CSP_API_TOKEN: ((marketplace_api_token))
            MARKETPLACE_ENV: staging
        on_failure:
          put: pull-requests
          inputs: detect
          params:
            path: source
            status: failure
      - put: pull-requests
        inputs: detect
        params:
          path: source
          status: success

  - name: build
    serial_groups: [ version ]
    plan:
      - in_parallel:
          - get: source
            passed:
              - test
            trigger: true
          - get: version
            params:
              pre: rc
      - task: build-cli
        file: source/ci/tasks/build.yaml
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: harbor-repo.vmware.com/dockerhub-proxy-cache/concourse/oci-build-task
              username: ((harbor.username))
              password: ((harbor.token))
          inputs:
            - name: build
            - name: source
          outputs:
            - name: image
          params:
            DOCKERFILE: source/Dockerfile
          run:
            path: build

      - put: mkpcli
        inputs: [ image, version ]
        params:
          image: image/image.tar
          additional_tags: version/version  # Update the parameter list if/when concourse is updated
#      - put: release
#        inputs: [ build, source, version ]
#        params:
#          name: version/version
#          tag: version/version
#          tag_prefix: v
#          commitish: source/.git/ref
#          globs:
#            - build/*
      - put: version
        inputs: detect
        params:
          file: version/version

#  - name: bump-major-version
#    serial_groups: [version]
#    plan:
#      - put: version
#        inputs: detect
#        params:
#          bump: major

  - name: bump-minor-version
    serial_groups: [version]
    plan:
      - put: version
        inputs: detect
        params:
          bump: minor

  - name: test-container-product
    plan:
      - in_parallel:
          - get: nginx-image
          - get: test-container-product-version
            params: { bump: patch }
          - get: mkpcli
            trigger: true
            passed: [build]
          - get: source
            passed: [build]
          - get: version
            passed: [build]
      - task: add-version-to-marketplace
        image: mkpcli
        file: source/ci/tasks/add-version.yaml
        input_mapping: {version: test-container-product-version}
        params:
          SLUG: test-container-product-41
      - put: test-container-product-version
        inputs: detect
        params:
          file: test-container-product-version/version
      - task: add-container-image-to-marketplace
        image: mkpcli
        config:
          inputs:
            - name: nginx-image
            - name: test-container-product-version
          platform: linux
          params:
            CSP_API_TOKEN: ((marketplace_api_token))
            MARKETPLACE_ENV: staging
            SLUG: test-container-product-41
          run:
            path: bash
            args:
              - -exc
              - |
                mkpcli container-image create \
                  --product ${SLUG} \
                  --product-version $(cat test-container-product-version/version) \
                  --image-repository bitnami/nginx \
                  --image-tag $(cat nginx-image/tag) \
                  --image-tag-type FIXED \
                  --deployment-instructions "docker run bitnami/nginx:$(cat nginx-image/tag)"

  - name: test-chart-product
    plan:
      - in_parallel:
          - get: nginx-chart
            params:
              skip_download: true
          - get: test-chart-product-version
            params: { bump: patch }
          - get: mkpcli
            trigger: true
            passed: [build]
          - get: source
            passed: [build]
          - get: version
            passed: [build]
      - task: add-version-to-marketplace
        image: mkpcli
        file: source/ci/tasks/add-version.yaml
        input_mapping: {version: test-chart-product-version}
        params:
          SLUG: test-chart-product-42
      - put: test-chart-product-version
        inputs: detect
        params:
          file: test-chart-product-version/version
      - task: add-chart-to-marketplace
        image: mkpcli
        config:
          inputs:
            - name: nginx-chart
            - name: test-chart-product-version
          platform: linux
          params:
            CSP_API_TOKEN: ((marketplace_api_token))
            MARKETPLACE_ENV: staging
            SLUG: test-chart-product-42
          run:
            path: bash
            args:
              - -exc
              - |
                mkpcli chart create \
                  --product ${SLUG} \
                  --product-version $(cat test-chart-product-version/version) \
                  --chart-name nginx \
                  --chart-version $(cat nginx-chart/version) \
                  --chart-url https://charts.bitnami.com/bitnami \
                  --repository-name nginx \
                  --repository-url https://charts.bitnami.com/bitnami

  - name: test-ova-product
    plan:
      - in_parallel:
          - get: test-ova-product-source
            trigger: true
          - get: test-ova-product-version
            params: { bump: patch }
          - get: mkpcli
            trigger: true
            passed: [build]
          - get: source
            passed: [build]
          - get: version
            passed: [build]
      - task: download-ova
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/buildpack-deps
              tag: buster
              username: ((harbor.username))
              password: ((harbor.token))
          inputs:
            - name: test-ova-product-source
          outputs:
            - name: test-ova-product-source
          run:
            path: make
            dir: test-ova-product-source/test-ova-product
            args: [ check ]
      - task: add-version-to-marketplace
        image: mkpcli
        file: source/ci/tasks/add-version.yaml
        input_mapping: {version: test-ova-product-version}
        params:
          SLUG: test-ova-product-11
      - put: test-ova-product-version
        inputs: detect
        params:
          file: test-ova-product-version/version
      - task: add-ova-to-marketplace
        image: mkpcli
        config:
          inputs:
            - name: test-ova-product-source
            - name: test-ova-product-version
          platform: linux
          params:
            CSP_API_TOKEN: ((marketplace_api_token))
            MARKETPLACE_ENV: staging
            SLUG: test-ova-product-11
          run:
            path: bash
            args:
              - -exc
              - |
                mkpcli ova create \
                  --product ${SLUG} \
                  --product-version $(cat test-ova-product-version/version) \
                  --ova-file test-ova-product-source/test-ova-product/*.ova

  - name: release
    serial_groups: [ version ]
    plan:
      - in_parallel:
        - get: source
          passed:
            - test-chart-product
            - test-container-product
            - test-ova-product
        - get: version
          passed:
            - test-chart-product
            - test-container-product
            - test-ova-product
          params:
            bump: final
      - in_parallel:
        - do:
          - task: build-cli
            file: source/ci/tasks/build.yaml
          - task: build-image
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: harbor-repo.vmware.com/dockerhub-proxy-cache/concourse/oci-build-task
                  username: ((harbor.username))
                  password: ((harbor.token))
              inputs:
                - name: build
                - name: source
              outputs:
                - name: image
              params:
                DOCKERFILE: source/Dockerfile
              run:
                path: build
        - do:
          - get: release
          - task: make-release-notes
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/golang
                  tag: 1.17
                  username: ((harbor.username))
                  password: ((harbor.token))
              inputs:
                - name: release
                - name: source
              outputs:
                - name: release-notes
              run:
                path: bash
                dir: source
                args:
                  - -exc
                  - |
                    git log $(cat ../release/tag)..HEAD --oneline | grep -v "\[ci skip\] bump version" > ../release-notes/notes.txt

      - put: mkpcli-public
        params:
          image: image/image.tar
          additional_tags: version/version
#      - put: release
#        inputs: [ build, source, version, release-notes ]
#        params:
#          name: version/version
#          tag: version/version
#          tag_prefix: v
#          commitish: source/.git/ref
#          body: release-notes/notes.txt
#          globs:
#            - build/*
#      - put: version
#        params:
#          bump: patch
